<?PHP
$INSTALL_ON_BOOT = $_POST['INSTALL_ON_BOOT'];
$UPGRADE_ON_BOOT = $_POST['UPGRADE_ON_BOOT'];
$UPGRADE_PLG_ON_BOOT = $_POST['UPGRADE_PLG_ON_BOOT'];
$START_ON_ARRAY_MOUNT = $_POST['START_ON_ARRAY_MOUNT'];
$START_VMS_ON_START = $_POST['START_VMS_ON_START'];
$VBOX_SYMLINK_LOCATION = $_POST['VBOX_SYMLINK_LOCATION'];
$VBOXWEBSRV_HOST_IP = $_POST['VBOXWEBSRV_HOST_IP'];
$VBOXWEBSRV_HOST_PORT = $_POST['VBOXWEBSRV_HOST_PORT'];
$VBOXWEBSRV_LOGFILE = $_POST['VBOXWEBSRV_LOGFILE'];
$VBOXWEBSRV_VERBOSE = $_POST['VBOXWEBSRV_VERBOSE'];
$VBOXWEBSRV_LOGROTATE = $_POST['VBOXWEBSRV_LOGROTATE'];
$VBOXWEBSRV_LOGSIZE = $_POST['VBOXWEBSRV_LOGSIZE'];
$VBOXWEBSRV_LOGINTERVAL = $_POST['VBOXWEBSRV_LOGINTERVAL'];

$arguments = "";
$arguments .= "INSTALL_ON_BOOT_NEW=\"$INSTALL_ON_BOOT\"\n";
$arguments .= "UPGRADE_ON_BOOT_NEW=\"$UPGRADE_ON_BOOT\"\n";
$arguments .= "UPGRADE_PLG_ON_BOOT_NEW=\"$UPGRADE_PLG_ON_BOOT\"\n";
$arguments .= "START_ON_ARRAY_MOUNT_NEW=\"$START_ON_ARRAY_MOUNT\"\n";
$arguments .= "START_VMS_ON_START_NEW=\"$START_VMS_ON_START\"\n";
$arguments .= "VBOX_SYMLINK_LOCATION_NEW=\"$VBOX_SYMLINK_LOCATION\"\n";
$arguments .= "VBOXWEBSRV_HOST_IP_NEW=\"$VBOXWEBSRV_HOST_IP\"\n";
$arguments .= "VBOXWEBSRV_HOST_PORT_NEW=\"$VBOXWEBSRV_HOST_PORT\"\n";
$arguments .= "VBOXWEBSRV_LOGFILE_NEW=\"$VBOXWEBSRV_LOGFILE\"\n";
$arguments .= "VBOXWEBSRV_VERBOSE_NEW=\"$VBOXWEBSRV_VERBOSE\"\n";
$arguments .= "VBOXWEBSRV_LOGROTATE_NEW=\"$VBOXWEBSRV_LOGROTATE\"\n";
$arguments .= "VBOXWEBSRV_LOGSIZE_NEW=\"$VBOXWEBSRV_LOGSIZE\"\n";
$arguments .= "VBOXWEBSRV_LOGINTERVAL_NEW=\"$VBOXWEBSRV_LOGINTERVAL\"\n";

echo "Please wait while updating configuration...";

$file = "/usr/local/emhttp/plugins/virtualbox/virtualbox.args";
file_put_contents($file, $arguments);
shell_exec("/etc/rc.d/rc.virtualbox updatecfg");
?>

<HTML>
<HEAD><SCRIPT>var goback=parent.location;</SCRIPT></HEAD>
<BODY onLoad="parent.location=goback;"</BODY>
</HTML>
